services:
  mongo:
    image: mongo
    networks:
      - mongodb_net
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    networks:
      - mongodb_net
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    depends_on:
      - mongo

  client:
    image: nginx:latest
    container_name: client
    ports:
      - "8080:80"
    volumes:
      - ./client/webroot:/usr/share/nginx/html:ro
    restart: unless-stopped

volumes:
  mongodb_data:
 
networks:
  mongodb_net: